// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ClickStartAutoSave","status":true,"description":"타이틀 메뉴 없이 클릭 한 번으로 시작하고, 진행 상황을 자동으로 저장/이어하기합니다.","parameters":{"startText":"꿈속으로 들어가기","textY":"-1","fontSize":"28","blink":"true","autosaveInterval":"60","saveOnTransfer":"true","saveOnExit":"true","saveOnToTitle":"true","hideSaveCommand":"true","shiftNewGame":"playtest"}},
{"name":"TerrainFootsteps","status":true,"description":"걸을 때마다 밟은 지형(지형 태그·리전)에 맞는 발소리를 냅니다.","parameters":{"tag0":"{\"name\":\"Step_Default\",\"volume\":\"35\",\"pitch\":\"100\"}","tag1":"{\"name\":\"Step_Grass\",\"volume\":\"40\",\"pitch\":\"100\"}","tag2":"{\"name\":\"Step_Dirt\",\"volume\":\"40\",\"pitch\":\"100\"}","tag3":"{\"name\":\"Step_Stone\",\"volume\":\"40\",\"pitch\":\"100\"}","tag4":"{\"name\":\"Step_Wood\",\"volume\":\"40\",\"pitch\":\"100\"}","tag5":"{\"name\":\"Step_Water\",\"volume\":\"45\",\"pitch\":\"100\"}","tag6":"{\"name\":\"Step_Snow\",\"volume\":\"40\",\"pitch\":\"100\"}","tag7":"{\"name\":\"\",\"volume\":\"40\",\"pitch\":\"100\"}","regionSounds":"[]","pitchVariance":"8","volumeVariance":"10","stepInterval":"1","disableSwitch":"0","duringMoveRoute":"true","followers":"false","followerVolume":"60"}},
{"name":"KeyboardMovement","status":true,"description":"맵에서 마우스 클릭 이동을 끄고, WASD 키로도 움직일 수 있게 합니다.","parameters":{"disableClickMove":"true","rightClickMenu":"true","wasd":"true","pageDownKey":"E"}}
];
